 ######### model parameter

models:
  model_warpper: Voice2Face
  conponents:
    F:
      model: SEResNet50IR
      freeze: False
      output_channel: 128
      num_classes: 924
      bn: BatchNorm
      act: ReLU
      vote: True
    V:
      model: ThinResNet34
      freeze: False
      output_channel: 128
      num_classes: 924
      bn: BatchNorm
      act: ReLU
    center:
      model: center
      output_channel: 128
      num_classes: 924

  normal_layer: True
  with_cross: True
  weight: True

  normal_mean:
    - 127.5
    - 127.5
    - 127.5
  normal_std:
    - 127.5
    - 127.5
    - 127.5

#### dataset define
dataset:
  modal: 'both'
  pair: False
  triple: False
  dataset_train: vox1_train
  dataset_val: vox1_val
  dataset_test: vox1_test
  eval_triplet_val: match_g_v2f_2_val
  eval_triplet_test: match_g_v2f_2_test
  image_data_dir: ./data/VGG_ALL_FRONTAL
  audio_data_dir: ./data/wav
  list_dir: ./data/list_wav
  resize:
    - 112
    - 112
  input_size:
    - 112
    - 112

######### train parameter
training:
  save_dir: ./save
  experiment_id: re-weighting
  ft: True
  optimizer:
    match:
      train_params:
        - F
        - V
        - center
      loss_weight:
        - 1.0
        - 1.0
        - 1.0
      optim_method: sgd
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
      lr_decay_iter:
        - 1000
        - 2000
      lr_decay: 0.1

  weight_update_iter: 100
  save_iter: 10000 # save a checkpoint
  max_iter: 2400
  num_workers: 8
  batchsize: 64
  no_cuda: False
  resume_train: none
